#!/usr/bin/env node
"use strict";

// Gate runner: stop hook. Runs test/lint/secret scan and writes .cursor/reports/gate-report.md.
// Reads JSON from stdin (hook input with workspace_roots).

const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");

function readStdin() {
  return new Promise((resolve) => {
    const chunks = [];
    process.stdin.on("data", (chunk) => chunks.push(chunk));
    process.stdin.on("end", () => resolve(Buffer.concat(chunks).toString("utf8")));
  });
}

function run(cwd, command, args = []) {
  try {
    const result = execSync(command, {
      cwd,
      encoding: "utf8",
      timeout: 120000,
      stdio: ["pipe", "pipe", "pipe"],
    });
    return { ok: true, output: result };
  } catch (e) {
    const output = (e.stdout || "") + (e.stderr || "");
    return { ok: false, output: output || e.message };
  }
}

function secretScan(cwd) {
  const patterns = ["password\\s*=\\s*['\"]", "api_key\\s*=\\s*['\"]", "secret\\s*=\\s*['\"]"];
  let found = [];
  try {
    const { execSync } = require("child_process");
    for (const p of patterns) {
      try {
        const out = execSync(`git grep -n -E "${p}" -- "*.ts" "*.js" "*.tsx" "*.json" "*.env*" 2>nul || true`, {
          cwd,
          encoding: "utf8",
          maxBuffer: 1024 * 1024,
        });
        if (out.trim()) found.push(out.trim().slice(0, 500));
      } catch (_) {}
    }
  } catch (_) {}
  return found.length === 0 ? { ok: true, note: "No obvious secrets in scanned files" } : { ok: false, note: "Possible secrets - review manually", matches: found };
}

async function main() {
  const raw = await readStdin();
  let input = {};
  try {
    input = JSON.parse(raw);
  } catch (_) {}
  const workspaceRoots = input.workspace_roots || [];
  const root = workspaceRoots[0] || process.cwd();
  const reportsDir = path.join(root, ".cursor", "reports");
  if (!fs.existsSync(reportsDir)) {
    try {
      fs.mkdirSync(reportsDir, { recursive: true });
    } catch (_) {}
  }

  const qa = run(root, "npm test", []);
  const lint = run(root, "npm run lint", []);
  const security = secretScan(root);

  const lines = [
    "# Gate Report",
    "",
    "Generated by gate-runner (stop hook). Treat this as source of truth for gate status.",
    "",
    "## QA (tests)",
    "",
    `- **Status:** ${qa.ok ? "PASS" : "FAIL"}`,
    `- **Command:** npm test`,
    "- **Output (summary):**",
    "```",
    (qa.output || "").slice(0, 2000),
    "```",
    "",
    "## Lint / typecheck",
    "",
    `- **Status:** ${lint.ok ? "PASS" : "FAIL"}`,
    `- **Command:** npm run lint`,
    "- **Output (summary):**",
    "```",
    (lint.output || "").slice(0, 2000),
    "```",
    "",
    "## Security (quick scan)",
    "",
    `- **Status:** ${security.ok ? "PASS" : "REVIEW"}`,
    `- **Note:** ${security.note || "N/A"}`,
    "",
    "## Docs",
    "",
    "- **Status:** Manual (ensure how-to test and config/env notes exist)",
    "",
    "---",
    "",
    "**Ready to merge when:** All gates above are PASS/REVIEW and no pending handoffs in handoffs.md.",
  ];

  const outPath = path.join(reportsDir, "gate-report.md");
  fs.writeFileSync(outPath, lines.join("\n"), "utf8");
}

main().catch(() => {});
